### ISSUE TITLE
Request for Access to Dataset - Completed Google Form Submission

### ISSUE THREAD

**Issue by arbab-ml** [UTokyo-FieldPhenomics-Lab/P2PNet-Soy#1]
Dear @oceam 

I hope this message finds you well. First and foremost, I would like to express my gratitude for your exceptional work, which has certainly made a significant contribution to the field.

I am writing to kindly request access to the dataset associated with your research. I have diligently completed the required Google Form, and I am eager to utilize the data for further exploration and analysis.

Your prompt response in granting access to the dataset would be greatly appreciated. If there is any additional information or requirements needed from my end, please do not hesitate to inform me.

Thank you once again for your valuable work, and I am looking forward to delving into the dataset.

Best regards,

Arbab

**Comment by arbab-ml** [comment]
@oceam @HowcanoeWang @ZJiangsan  Kindly consider a gentle reminder. 
Best, 

@ZJiangsan Kindly confirm if the data used for this paper was the same as used for MLCAS2022
https://github.com/ZJiangsan/MLCAS2022_Soypod_counting/issues/1

thanks

**Comment by HowcanoeWang** [comment]
@arbab97 The Dropbox download link should be sent to you automatically once you submit the form (we have just tested it still works), please check your spam inbox, or try again using a personal Gmail (apologize we could not paste the URL here directly)

The email title is "P2PNet-Soy dataset"

**Comment by arbab-ml** [comment]
I appreciate your help. I received the link. 
Thank you, 
Arbab

**Comment by arbab-isu** [comment]
Hello @HowcanoeWang 
Thank you for sharing your data and code. I've found it extremely beneficial for my research. I have, however, encountered a challenge that I hope you might be able to assist me with.
For my research, I am utilizing techniques that necessitate images of plants from a full 360-degree perspective. While it's not crucial for me to have an exhaustive collection, I do require images that cover all angles, including the corners of the plant.
Your test data provides something akin to what I need, as it includes images of the soybean plants from both the left and right sides. However, I am also in need of images from the remaining angles to complete the 360-degree coverage, even if these are limited in number.
Could you possibly have additional resources to assist with this? This could include a video or more pictures from your test data, or perhaps training data with more comprehensive images, as the current set primarily contains cropped photos.
Any advice or guidance you might be able to offer would be greatly appreciated.

Best, 
Arbab

**Comment by HowcanoeWang** [comment]
> Hello @HowcanoeWang 
> Thank you for sharing your data and code. I've found it extremely beneficial for my research. I have, however, encountered a challenge that I hope you might be able to assist me with.
> For my research, I am utilizing techniques that necessitate images of plants from a full 360-degree perspective. While it's not crucial for me to have an exhaustive collection, I do require images that cover all angles, including the corners of the plant.
> Your test data provides something akin to what I need, as it includes images of the soybean plants from both the left and right sides. However, I am also in need of images from the remaining angles to complete the 360-degree coverage, even if these are limited in number.
> Could you possibly have additional resources to assist with this? This could include a video or more pictures from your test data, or perhaps training data with more comprehensive images, as the current set primarily contains cropped photos.
> Any advice or guidance you might be able to offer would be greatly appreciated.
> 
> Best, 
> Arbab

@oceam Any ideas for comments for this?

**Comment by YZGod666** [comment]
Hello, I see in your paper that your training and verification data are 181 images and 193 images respectively, but the data automatically sent to me by Dropbox download link does not match the description of the data set in the paper. I hope you can answer my doubts. Thank you very much for your support
